# Generated by Django 3.1.7 on 2021-03-30 23:37

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='videos',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
