# Generated by Django 3.1.7 on 2021-04-02 05:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetCount', models.IntegerField(default=100, validators=[django.core.validators.MinValueValidator(0)])),
                ('currentCount', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('timeStart', models.DateTimeField(auto_now=True)),
                ('timeEnd', models.DateTimeField()),
                ('name', models.CharField(max_length=40)),
            ],
        ),
    ]
