# Generated by Django 3.1.7 on 2021-04-02 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_challenge_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='workoutName',
            field=models.CharField(default='Pushups', max_length=10),
        ),
    ]
