# Generated by Django 3.1.7 on 2021-04-01 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210331_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='videoUrl',
        ),
        migrations.AddField(
            model_name='video',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos/', verbose_name=''),
        ),
    ]
